# Generated by Django 2.1 on 2019-04-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190329_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='content',
            new_name='summary',
        ),
    ]
